### ISSUE TITLE
Allow HandlerScheduler to run immediately if on the correct thread

### ISSUE THREAD

**Issue by zpinter** [JakeWharton/NotRxAndroid#28]
Great to see the ideas in this project! I wanted to submit one more idea for feedback:

By default, the HandlerScheduler always calls postDelayed, even if ```delayTime <= 0 && Looper.myLooper() == handler.getLooper()```.

I've found it useful to have a scheduler that behaves more like ```Schedulers.immediate()``` in this scenario. The main benefits are immediate execution with no delay (nothing to schedule) and preservation of the call stack when debugging.

There's already enough hooks to swap out the default scheduler, but I'd be curious to see if anybody else finds this idea valuable and if it would be reasonable to make it the default behavior.

**Comment by JakeWharton** [comment]
We had another team do this internally, but I'm not sure how I feel about it. It's not that I'm opposed, more that I worry this creates code that relies on this behavior incorrectly and thus assumes synchronous execution which might not always be the case. I've certainly had problems because of this behavior manifest themselves, but in every case I was able to change or remove a call to get the correct behavior without needing to have the scheduler act in this way.

I'm curious what @dlew @mttkay and @loganj think here.

**Comment by loganj** [comment]
We've been writing code against an executor that behaves this way since well before we started using RxJava, so it's a natural fit and we haven't had any problems. Having our Views subscribe to Observables that can always supply some value, and observe on this scheduler, has made life pretty easy. It means we can safely subscribe in `onAttachedToWindow()`, for instance, and not worry about doing any out-of-band view initialization.

I've been reluctant to propose our scheduler for RxAndroid only because the sometimes-immediate, sometimes-not invocation does go a bit against the grain of the other schedulers. It's definitely been the right thing for us across three or four apps over the past year, though.

(Fun fact: We also have another one now that invokes when the UI thread is idle, but there's only one usage.)

**Comment by dlew** [comment]
Could I see a case where it helps, in particular? I'm having trouble coming up with a case where the immediate execution couldn't have just been achieved by simply *not* setting any `Schedulers` in the first place.

**Comment by mttkay** [comment]
we've had endless discussions around this back when the Android module was
part of core and rejected multiple PRs that introduced this on a whim. I
was always against it, as it introduces a certain unpredictability to
scheduling. Right now the contract is clear: it dispatches a notification
through the given looper. I also remember that it broke recursive
scheduling, although I'm not sure that's still an issue.

I'll see if I can dig up some of the discussion that happened back then.

**Comment by mttkay** [comment]
For reference: https://github.com/ReactiveX/RxJava/pull/1102

**Comment by dlew** [comment]
After sleeping on it, some thoughts:

Imagine you've got this sequence, created in the main thread:

```java
retrofit.someNetworkCall()
  .subscribeOn(Schedulers.io())
  .observeOn(AndroidSchedulers.mainThread())
  .subscribe()
```

You *need* `observeOn()` for this sequence, as otherwise it would `onNext` via the IO `Scheduler`. Removing `subscribeOn()` means that `observeOn()` would also become unnecessary. This optimization doesn't help the common case.

The only time this optimization would help is if you're passed an Observable which may or may not have had `subscribeOn` already applied to it, as such:

```java
void someMethod(Observable possiblyAsyncObservable) {
  possiblyAsyncObservable
    .observeOn(AndroidSchedulers.mainThread())
    .subscribe()
}
```

The optimization would essentially re-do the same logic as above - that without `subscribeOn`, `observeOn` is also unnecessary (if you want to run in the same thread).

...I still haven't decided whether the optimization is something I like or not. This is yet another good argument for deferring `subscribeOn` and `observeOn` until subscription, though.

**Comment by mttkay** [comment]
We "solved" this problem by establishing shared practices around whose
responsibility it is to schedule and/or observe a sequence. When doing
that, you practically never end up composing streams that have already been
scheduled by another entity.

**Comment by loganj** [comment]
Interesting. Our rule has been "if you care what thread you're observing/subscribed on, calling `observeOn`/`subscribeOn` is your responsibility". In practice, we very rarely end up with more than a `subscribeOn` for an originating Observable and an `observeOn` right before touching the UI.

`mainThread()` being sometimes-synchronous isn't a performance optimization for us, it's a behavioral guarantee that makes it safe to _only_ rely on observables to keep a View updated.  As I mentioned before, we nearly always subscribe to an observable (usually BehaviorSubjects, ultimately) in `onAttachedToWindow()`, and thanks to `mainThread()` those subscribers fire synchronously so our view is guaranteed to be populated before it's visible. That subscription then  keeps the view updated until we unsubscribe it in `onDetachedFromWindow()`.

If we used a scheduler that always posted like HandlerScheduler, we'd have to populate the view from some other source before allowing it to become visible, which is just extra complexity.

**Comment by mttkay** [comment]
> being sometimes-synchronous isn't a performance optimization for us, it's
a behavioral guarantee

I guess that's the bit I'm struggling with. How is anything that is
sometimes-synchronous a guarantee of behavior? ^^

**Comment by loganj** [comment]
Ha. It's a guarantee predicated on the observable.  If that observable can emit a value immediately, you'll get it synchronously. Our model observables always have values.

```java
model.observeOn(mainThread()).subscribe(populateView)
```

The observable model is the single source of truth, it always has a value, and you can always observe it on `mainThread()` and have a correctly populated view. That's the guarantee that `mainThread()` helps us with.

The view is initialized synchronously from the model and then kept up to date as we push updates into the model.  We _don't_ have to separately `model.get()` and `model.observe()`, so we don't have to worry about a distinction or races between synchronous initialization and asynchronous update. 

I completely understand your POV here though, and it's why I haven't prescribed this scheduler for anyone else.

**Comment by mttkay** [comment]
Ah--gotcha. Yeah that makes sense. A related question: you mention
mainThread(), so am I assuming correctly you're injecting a different
implementation for that operator via the plugin API?

**Comment by loganj** [comment]
Oh, that would be _much_ smarter. No, we just have our own class/import for it.

**Comment by JakeWharton** [comment]
The plugin API was added recently in RxAndroid and hasn't been in a release yet.

**Comment by mttkay** [comment]
Actually, just to throw in another problem that might be related to this. We started having problems in the app recently related to back pressure (or the lack thereof), where notifications would start to pile up in RxJava's internal buffers and make them eventually overflow. Our theory is that the main looper is failing to catch up on events that are arriving, possibly because there's simply too much work being done on the main thread. Most of our observables sit in the business and data layers and are actually "scalar" (or "singular" to use the nomenclature that will apparently be used going forward...), but we do make heavy use of event queues (Subjects, essentially) to propagate things like tracking events or progress events from the player, which are obviously not scalar.

Back to this issue, whether or not these events actually originated from the main thread already (which would make this issue here relevant) or not we're still investigating. But said that, did you guys ever run into cases where you had to apply back pressure, and if so, does the change in behavior you propose help to address this?

**Comment by dlew** [comment]
Interesting - have you tried using the plugin to inject this alternative version of the main thread handler? I would check that out and see if it's still happening.

Alternatively, the RxAndroid ring buffer is extraordinarily small. Are you running into it with the default size?

**Comment by loganj** [comment]
I haven't had backpressure issues on the main thread, just on the io scheduler when it was getting spammed pretty hard.

That said, it's not clear to me how this behavior change would result in fewer events in the queue, so I'll be surprised if it helps.

**Comment by mttkay** [comment]
> Alternatively, the RxAndroid ring buffer is extraordinarily small. Are you running into it with the default size?

Yes--the default size is 16, so this overflows very quickly once there is congestion on the looper. Basically what happens is that OperatorObserveOn is `offer`ing notifications to its internal queue faster than it's being drained, and the draining happens only when the scheduled actions gets processed by Android's message queue.

**Comment by mttkay** [comment]
@loganj Because it would short circuit in `schedule` and not post anything to the main looper. That would  potentially reduce congestion, assuming there are many events being scheduled that *originate* from the main thread.

**Comment by JakeWharton** [comment]
The schedulers have been removed. Bring up an issue on RxAndroid if you want to discuss further.
